# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://539go.com
# 资源地址默认和url相同 https://assets.539go.com
assetsurl: https://assets.539go.com
date_format: "ordinal"
title: 梁先生的 blog
subtitle: "Simple philosophy,梁先生的 blog"
description: "记录一些开发笔记、日常等"
keywords: Unity, Android, Python, 编程, 勿语, 梁先生的博客,博客，游戏开发,软件分享
favicon: /favicon.ico
timezone: Test
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Liangddyy
organization: 。
organization_url: 。
github_username: liangddyy
location: Fuzhou, China
email: liangddyy@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: categories

  -
    href: /wiki/
    label: wiki

  -
    href: /about/
    label: about
    #   -
#     href: /links/
#     label: 链接

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: liangddyy/liangddyy.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, other
# other 有言评论(已弃用)
comments_provider: other
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: liangdy

# http://539go.com/posts/gitment-introduction/
gitment:
    owner: liangddyy
    repo: liangddyy.github.io
    oauth:
        client_id: b7613820ffb01a4f67de
        client_secret: 06cdb25193a18aed6acd864fcb1049eac1af2d54
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    # analytics_id: 
    #UA-80669434-1
